### ISSUE TITLE
Yeni Sürüm Geçişi

### ISSUE THREAD

**Issue by Muratbaykam** [Muratbaykam/visual-bot-eski#2]
## Yeni Sürüm Hakkında

Eski botun üzerine yenisini kurayım falan yapmayınız , yeni botun boyutu yüksek olduğundan eski botun üzerine biniyor.

Ayrıca VDS Hatası alanlar lütfen bana ulaşsın :+1: 

Discord : **Murat$Baykam#7545**

**Comment by Serhann** [comment]
Lütfen Github'u kullanmayı öğren..

**Comment by ghost** [comment]
D:\YUNUS\BOT 2\Visual Bot Legend V2\bot.js:199
});
  ^

SyntaxError: Unexpected end of input
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)

Hatası veriyor napabilirim

**Comment by ghost** [comment]
ama bot.js klasörunde 199 satır yok
